apiVersion: v1
kind: Secret
metadata:
  name: "github-user-token"
  namespace: "ci"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "GitHub credentials"
type: Opaque
stringData:
  username: 'sebge2emasphere'
  password: '612a7743dd661ada7fee6ff31c0c1c8b7a2e4723'

---

apiVersion: v1
kind: Secret
metadata:
  name: "slack-integration-id"
  namespace: "ci"
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
    "jenkins.io/credentials-description" : "Slack credentials"
type: Opaque
stringData:
  text: "7Ir6cBHZJDX7nSLlLmZEHOot"

---

apiVersion: v1
kind: Secret
metadata:
  name: "mail-credentials"
  namespace: "ci"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "Mail Credentials"
type: Opaque
stringData:
  username: 'AKIA4HIBN7SKML5BBRNX'
  password: 'BAkMU+wFgCKv4XHn3+2G0tTUV66GqhI1b879JYkAZjVD'
---

apiVersion: v1
kind: Secret
metadata:
  name: "postgres-credentials"
  namespace: "ci"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "Postgres Credentials"
type: Opaque
stringData:
  username: 'ci'
  password: 'HRP6fL8yXhmpp8ze'
