apiVersion: v1
kind: Secret
metadata:
  name: "github-user-token"
  namespace: "ci"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "GitHub user token secret"
type: Opaque
stringData:
  username: 'sebge2emasphere'
  password: '612a7743dd661ada7fee6ff31c0c1c8b7a2e4723'

---

