pipeline {
    agent {
        kubernetes {
          label 'mobile-build'
          yaml """
spec:
  imagePullSecrets:
    - name: com.emasphere.dev.ecr
  containers:
  - name: nodejs
    image: 840205991060.dkr.ecr.eu-central-1.amazonaws.com/dev/jenkins-nodejs:1.0.1
    imagePullPolicy: Always
    command:
    - cat
    tty: true
"""
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    stages {
      stage('Checkout') {
         steps {
            git branch: 'master',
                credentialsId: 'b35f24b1-359a-41b4-a342-c1bddbd4b9b8',
                url: 'https://github.com/EMAsphere/mobile.git'
         }
      }
      stage('Install') {
             steps {
                container('nodejs') {
                    sh 'ls -al /usr/local/bin/'
                     sh 'sleep 120'
                    sh "npm install"
                }
             }
      }
      stage('Build') {
         steps {
            sh "npm run build"
         }
      }
    }

    post {
        changed {
                    emailext subject: '$DEFAULT_SUBJECT',
                        body: '$DEFAULT_CONTENT',
                        replyTo: '$DEFAULT_REPLYTO',
                        to: 'sgerard@emasphere.com'
        }
        failure {
                    emailext subject: '$DEFAULT_SUBJECT',
                        body: '$DEFAULT_CONTENT',
                        replyTo: '$DEFAULT_REPLYTO',
                        to: 'sgerard@emasphere.com'
        }
    }
}
